name: Android Build When added tag

on:
  push:
    tags:
      - 'featurez'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run all test
        run: ./gradlew test

      - name: Build debug APK and AAB after test
        run: |
                ./gradlew test
                ./gradlew assembleDebug
                ./gradlew bundleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/release/app-debug.apk

      - name: Show Build Info
        run: echo "This job is ${{ job.status }} on ${{github.ref}} in ${{ github.repository }} with ${{runner.os}}"