name: Android CI TAG

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Show Build Info
        run: echo "This job is ${{ job.status }} on ${{github.ref}} in ${{ github.repository }} with ${{runner.os}}"